### ISSUE TITLE
plover_vi has no attribute 'KEYS'

### ISSUE THREAD

**Issue by aerickt** [user202729/plover_vi#1]
I installed the plugin from the GitHub repo `pip install git+https://github.com/user202729/plover_vi`. And when I switch the system, the following error shows up:
```
ERROR: Qt GUI error
AttributeError: module 'plover_vi' has no attribute 'KEYS'
```
After closing the configure window, clicking on the configure button again brings up the following:
```
ERROR: Qt GUI error
AttributeError: 'Engine' object has no attribute 'config'
```

Output when running Plover from terminal:
```
2021-11-27 09:31:35,500 [MainThread] ERROR: Qt GUI error
Traceback (most recent call last):
  File "/home/user/Applicationsplover/plover/config.py", line 375, in __getitem__
    value = opt.validate(self, key, opt.getter(self, key))
  File "/home/user/Applicationsplover/plover/config.py", line 242, in getter
    return config._config[section][option]
  File "/usr/lib64/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'System: Vietnamese'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Applicationsplover/plover/gui_qt/config_window.py", line 516, in on_option_changed
    self._config.maps[1][dependent.option_name] = update_fn(value)
  File "/home/user/Applicationsplover/plover/gui_qt/config_window.py", line 414, in <lambda>
    ('system_keymap', lambda v: self._update_keymap(system_name=v)),
  File "/home/user/Applicationsplover/plover/gui_qt/config_window.py", line 491, in _update_keymap
    return self._engine[('system_keymap',
  File "/home/user/Applicationsplover/plover/engine.py", line 75, in _with_lock
    return func(self, *args, **kwargs)
  File "/home/user/Applicationsplover/plover/engine.py", line 447, in __getitem__
    return self._config[setting]
  File "/home/user/Applicationsplover/plover/config.py", line 377, in __getitem__
    value = opt.default(self, key)
  File "/home/user/Applicationsplover/plover/config.py", line 239, in default
    return build_keymap(config, key)
  File "/home/user/Applicationsplover/plover/config.py", line 227, in build_keymap
    keymap = Keymap(machine_class.get_keys(), system.KEYS + machine_class.get_actions())
AttributeError: module 'plover_vi' has no attribute 'KEYS'
2021-11-27 09:31:36,815 [Dummy-1] ERROR: engine update failed
Traceback (most recent call last):
  File "/home/user/Applicationsplover/plover/config.py", line 375, in __getitem__
    value = opt.validate(self, key, opt.getter(self, key))
  File "/home/user/Applicationsplover/plover/config.py", line 242, in getter
    return config._config[section][option]
  File "/usr/lib64/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'System: Vietnamese'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Applicationsplover/plover/engine.py", line 147, in run
    if func(*args, **kwargs):
  File "/home/user/Applicationsplover/plover/engine.py", line 191, in _update
    config = self._config.as_dict()
  File "/home/user/Applicationsplover/plover/config.py", line 391, in as_dict
    return {opt.name: self[opt.name] for opt in self._OPTIONS.values()}
  File "/home/user/Applicationsplover/plover/config.py", line 391, in <dictcomp>
    return {opt.name: self[opt.name] for opt in self._OPTIONS.values()}
  File "/home/user/Applicationsplover/plover/config.py", line 377, in __getitem__
    value = opt.default(self, key)
  File "/home/user/Applicationsplover/plover/config.py", line 239, in default
    return build_keymap(config, key)
  File "/home/user/Applicationsplover/plover/config.py", line 227, in build_keymap
    keymap = Keymap(machine_class.get_keys(), system.KEYS + machine_class.get_actions())
AttributeError: module 'plover_vi' has no attribute 'KEYS'
2021-11-27 09:31:38,755 [MainThread] ERROR: Qt GUI error
Traceback (most recent call last):
  File "/home/user/Applicationsplover/plover/gui_qt/main_window.py", line 236, in on_configure
    self._configure()
  File "/home/user/Applicationsplover/plover/gui_qt/main_window.py", line 185, in _configure
    self._activate_dialog('configuration', manage_windows=manage_windows)
  File "/home/user/Applicationsplover/plover/gui_qt/main_window.py", line 161, in _activate_dialog
    dialog = self._active_dialogs[name] = dialog_class(self._engine, *args)
  File "/home/user/Applicationsplover/plover/gui_qt/config_window.py", line 424, in __init__
    self._update_config()
  File "/home/user/Applicationsplover/plover/gui_qt/config_window.py", line 464, in _update_config
    for name, value in self._engine.config.items()
AttributeError: 'Engine' object has no attribute 'config'
```

I'm running Plover from source, but I also get the exact same error when running the dev10 AppImage.

**Comment by aerickt** [comment]
Also, (not sure if a new issue should be created) would it be possible to create a JSON dictionary to make it easier to switch between English and Vietnamese (since this system uses the English layout as well)?

**Comment by user202729** [comment]
For now this system is kind of abandoned, I stick with the v1 one because I'm very comfortable with it already, and it takes a lot of time to relearn

(although it has no phrasing system, otherwise can only type 1 word per stroke, many words requires significant hand contortion etc.)

------

I just want to share some code I used to construct as a (Cartesian product) of the pronunciation (basically a systematic/logical deconstruction of the syllable into small learnable parts)

------

Actually (according to the discussion post) you're not supposed to switch system at all, so the plover.system entry point was a mistake. Should fix soon.

**Comment by user202729** [comment]
For reference, the installation instruction is linked in README at https://github.com/openstenoproject/plover/discussions/1312#discussioncomment-716949

**Comment by aerickt** [comment]
Oh I see. Thanks for the response.
